[versions]
build-config = "6.0.7"
dokka = "2.1.0"
gradle-versions = "0.53.0"
koja = "0.1.1" # will be substituted
kotlin = "2.3.10"
kotlinx-serialization = "1.10.0"
ksp-api = "2.3.5"
maven-publish = "0.36.0"
spotless = "8.1.0"

[plugins]
build-config = { id = "com.github.gmazzo.buildconfig", version.ref = "build-config" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gradle-versions = { id = "com.github.ben-manes.versions", version.ref = "gradle-versions" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
ondrsh-koja = { id = "sh.ondr.koja", version.ref = "koja" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
kotlin-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlin-gradle-api = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api", version.ref = "kotlin" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp-api" }
ksp-gradle-plugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp-api" }
